프로필 페이지 UI 완성
prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong pull request #11
Opened 2023-09-09 15:44 UTC by hyesung99

## 🪄 변경사항
## ✨ [페이지/컴포넌트 이름]

### 1. useCarousel
profile/hooks/useCarousel.ts

input ⇒ 현재 아이템 인덱스, 아이템 인덱스 setter 함수, 총 인덱스
output ⇒ ref

캐러샐로 사용할 컨테이너에 ref달아주면 index를 컨트롤해주는 캐러샐을 만들어 줍니다.

MIN_DISTANCE보다 많이 화면을 잡아서 움직이면 전달받은 세터 함수를 통해 인덱스를 +1 or -1해줍니다. 인덱스를 기준으로 캐러샐을 움직입니다.

### 2.Carousel

useCarousel에 의존하여 캐러샐을 구현합니다. 각 탭마다 컴포넌트가 들어갈 예정입니다.

selectedTabIndex에 의존하여 화면을 표현합니다.

모든 로직은 useCarousel에 위임했습니다.

### 3.ProfileTabs

ProfileCarousel과 마찬가지로 selectedTabIndexState에 의존하여 선택된 탭의 스타일을 변경해 줍니다. 탭을 클릭하면 selectedTabIndex 상태를 자신의 인덱스로 교체합니다.

<--
변경사항을 적을 때,
### 을 통해 변경사항을 한줄로 적어주세요. 커밋 기준으로 잘게 자를 수록 좋습니다.
추가적인 설명은 그 아래 일반 크기 글자로 적어주세요.
-->

## 🖥 결과 화면
![image](https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/42764685/f48dfd66-968e-4382-8d7e-c0b0d245f99c)
~푸터 사이즈 조정해주세요~

## ✏️ PR 포인트

작업을 너무 큰 단위로 잡아서 이것저것 변경이 많네요ㅠㅠ 다음에는 더 잘게 쪼개도록 하겠읍니다.

2023-09-10 08:55 UTC, sscoderati requested changes
리뷰 완료입니다! 주말동안 고생하셨습니다 혜성님!

2023-09-10 08:55 UTC, sscoderati commented on src/pages/profile/hooks/useCarousel.ts
> +        selectedTabIndex < totalIndex
개인적으로는 조건들을 따로 함수로 분리해서 어떤 조건인지 의미를 알 수 있는 이름을 붙여주시는게 좋지 않을까합니다!

2023-09-10 08:55 UTC, sscoderati commented on src/pages/profile/hooks/useCarousel.ts
> +        selectedTabIndex < totalIndex
```suggestion
        distanceX > 0 &&
        Math.abs(distanceX) > MIN_DISTANCE &&
        selectedTabIndex > 0
      ) {
        setSelectedTabIndex(selectedTabIndex - 1);
      } else if (
        distanceX < 0 &&
        Math.abs(distanceX) > MIN_DISTANCE &&
        selectedTabIndex < totalIndex - 1
```

selectedTabIndex는 `totalIndex - 1`과 비교하는 조건이어야 마지막 탭에서도 우측으로 탭을 넘길 수 있는 문제가 일어나지 않을 것 같습니다

2023-09-10 12:42 UTC, sgd122 commented
코드는 보지못했지만 하나의 기능에 대해서 변경되는 파일이 엄청...많군요? ㄷ

2023-09-10 13:05 UTC, suyeon1218 requested changes
혜성님 코맨트 확인해주시고 혜성님이 보시기에 우선은 뒤로 미뤄도 될 수정사항이라고 보시면 approve 로 바꾸겠습니다! Profile 페이지를 이렇게 빨리 완성하시다니... 👍  수고 많으셨습니다!

2023-09-10 13:05 UTC, suyeon1218 commented on src/pages/profile/components/ProfileCarousel/ProfileCarousel.style.ts
> +`;
`p4`

우선은 영역을 확인하시기 위해 임의로 상하좌우 전부다 border 속성을 주신걸까요?

2023-09-11 00:28 UTC, hyesung99 commented on src/pages/profile/states/selectedTabIndex.ts
오호 이런 방법도 있군요 라우팅처리해서 param으로 만들기...!
저는 swipe했을 때 넘길 페이지의 모습을 살짝 보여주고 싶어서 캐러샐형태로 만들었는데 음...
이 방식이 나아보이기도 하네요!

이 방식은 좀 더 고려해보고 필요하면 브랜츠를 새로 만들어서 수정해보겠습니다!

2023-09-11 00:28 UTC, hyesung99 commented on src/components/Button/index.tsx
>  }: ButtonProps) => (
좋아요! 수정했습니다

2023-09-11 01:08 UTC, sscoderati commented on src/pages/profile/Profile.tsx
> +        <ProfileCarousel totalIndex={PROFILE_TABS.TOTAL_INDEX} />
음... 데이터 받아올 때 임의로 TAB과 똑같은 키를 할당해서 가져오면
```jsx
 <ProfileTabs>
  {Array.from(PROFILE_TAB_LABELS).map(([key, value], index) => (
    <ProfileTabItem
      key={key}
      title={`${data[key]} ${value}`}
      index={index}
    />
  ))}
 </ProfileTabs>
```

대충 이런 느낌으로 불러올 수 있지 않을까 합니다.. 일단 데이터 받아보고 결정해도 괜찮을 것 같네요!

2023-09-11 01:09 UTC, suyeon1218 commented on src/pages/profile/components/ProfileConfig/ProfileConfig.tsx
해당 컴포넌트에 디엠 메세지, 환경설정, 프로필 수정 (혹은 팔로잉) 버튼이 들어가는 거라면 세팅과 관련없는 버튼도 들어 있는데 Config 만으로 의미 전달이 충분할까요?_?

2023-09-11 01:10 UTC, sscoderati commented on src/pages/profile/hooks/useCarousel.ts
> +        selectedTabIndex < totalIndex
잉 오늘 확인해보니까 잘 되네요? 오히려 -1 조건에서는 마지막 탭으로 절대 갈 수가 없는... ㅋㅋㅋ

2023-09-11 01:11 UTC, suyeon1218 commented on src/pages/profile/Profile.tsx
> +          />
1. 전 상위 컴포넌트를 추상화 시키고 하위 컴포넌트를 더 구체화 시키는 게 더 깔끔하다고 생각해서 입니다!
2. 그리고 `ProfileTabs` 의 하위 컴포넌트가 ProfileTabsItem` 이라면 굳이 `Profile` 페이지에서 불러올 필요가 있을까...? 하는 생각이 들어요!
3. prop 을 넘겨주게 되면 ProfileTabs 에 다양한 prop 을 넣어서 다른 탭들도 만들 수 있을 거라고 생각해요!

2023-09-11 01:12 UTC, sscoderati approved these changes

2023-09-11 07:52 UTC, hyesung99 commented on src/pages/profile/components/ProfileConfig/ProfileConfig.tsx
아하 DM버튼이 있으니 전부 설정관련은 아니군요...!

2023-09-11 08:47 UTC, hyesung99 commented on src/pages/profile/components/ProfileConfig/ProfileConfig.tsx
ProfileHeaderSection 이 더 좋겠네요!!

2023-09-11 09:02 UTC, hyesung99 commented on src/pages/profile/Profile.tsx
> +          />
넵 이부분은 확실히 개선의 여지가 많은 부분인것 같아요!
일단 내용이 너무 많으니 새로 브랜치 파서 수정해보겠습니다ㅠㅠ
일단 기능에는 문제 없습니다!

2023-09-11 09:17 UTC, suyeon1218 approved these changes

2023-09-11 09:19 UTC, merged