✨ common/PostPreview UI 개발
prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong pull request #14
Opened 2023-09-11 02:28 UTC by suyeon1218

## 🪄 변경사항

### PostPreview 컴포넌트 구현

`post` 페이지와 `profile` 페이지에서 사용할 `<PostPreview />` 컴포넌트를 작성하였습니다.

컴포넌트 설명은 [노션](https://www.notion.so/prgrms/common-PostPreview-e7f15214c08145bf9feedcb099b4fabe?pvs=4) 을 참조해주세요.

## 🖥 결과 화면

<img width="526" alt="PostPreview" src="https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/80307321/04915ee6-b8c6-4a6e-aa72-cfb0f6c5444a">

## ✏️ PR 포인트

### 데이터
- 현재 데이터를 받아서 처리한다고 가정하고 만든 상태입니다.
- 화면은 임의로 데이터를 넣어서 만들어봤습니다.

### UI
- 더보기 대신 네이버 블로그와 비슷하게 100자를 보여주고 나머지 글자는 `...` 으로 처리합니다.
- 이를 위해 substring 으로 문자열을 잘랐습니다. (+ 혹시 몰라 CSS 속성도 추가)
- mouse hover 시 UI 를 고민해본 뒤 적용할 예정입니다.
- 더 적합한 아이콘을 찾아볼 예정입니다.

### 기능
- 추후 Link 태그를 이용하여 `Profile` 페이지나 `Post/Detail/:postId` 페이지로 이동시켜야 합니다.

2023-09-11 03:39 UTC, imb96 approved these changes
LGTM 👍

2023-09-11 03:39 UTC, imb96 commented on src/components/PostPreview/PostPreview.tsx
> +      <PostContent>{previewTitle}...</PostContent>
말줄임표를 이렇게 할 수도 있군요

2023-09-11 07:39 UTC, hyesung99 requested changes

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.tsx
> +        <AvatarWrapper>
여기는 container로 사용해야겠네요!

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.tsx
> +      <PostContent>{previewTitle}...</PostContent>
보여줄 컨텐츠의 길이와 줄임표는 스타일로 지정하는게 더 좋지 않을까요??
webkit의 line-clamp속성을 적용하면 될 것 같습니다!
textEllipsis스타일은 provider style에 미리 만들어뒀으니 참고해서 적용하시면 될 것 같아요!

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.tsx
> +import type Post from '@types/Post';
Post type은 types/index.ts에서 export하고 있으니 @types에서 import 받아 주세요!

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.tsx
> +}
```suggestion
interface PostPreviewProps {
  previewPostData: Pick<
    Post,
    'image' | 'likes' | 'comments' | 'title' | 'author' | 'createdAt'
  >;
  noneProfile: boolean;
}
```
이런식으로 컴포넌트 내부에서 실제로 사용하는 데이터만 prop으로 받아야하지 않을까요? 
지금은 PostPreview컴포넌트를 사용하려면 팔로워나 팔로잉같은 데이터도 넘겨줘야 사용할 수 있는 상태인 것 같아요!

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.tsx
> +  const totalComments = comments.length;
처음부터 totalLIkes를 외부에서 prop으로 받는게 더 자연스럽지 않을까요?.?

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.tsx
> +  const PostHeader = noneProfile === true ? PostHeaderWithUser : PostDetailInfo;
noneProfile로 비교되는 두 대상의 네이밍의 공통점이 잘 안보여서 어떤 비교인지 모호한 것 같아요
```suggestion
  const PostHeader = noneProfile === true ? PostHeaderWithProfile : PostHeaderNoneProfile;
```
이런식은 어떨까요?

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.tsx
> +  const PostHeader = noneProfile === true ? PostHeaderWithUser : PostDetailInfo;
프로필없이 포스트 프리뷰를 보여주는 경우는 어떤 경우인가요?

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.style.ts
> +  align-items: center;
아직 머지는 안됐지만 프로바이더를 통해
```tsx
${({theme})} => theme.style.flexAlignCenter
```
이런식으로 활용할 수 있습니다!

2023-09-11 07:39 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.style.ts
> +  color: ${({ theme }) => theme['greyLight']};
```suggestion
  color: ${({ theme }) => theme.color.greyLight;
```
color프로바이더를 분리했기 때문에 theme.color.greyLight형식으로 사용해야 합니다!
빨리 공통 스타일 브랜치가 머지 되야 할텐데ㅠ
머지 되면 pull받고 수정해주세요!

2023-09-11 09:17 UTC, hyesung99 approved these changes
일단 Approve해둘게요!
리뷰 참고하셔서 적용 해볼만한거 적용하시고 머지하시면 될 것 같습니다!

2023-09-12 03:20 UTC, suyeon1218 commented on src/components/PostPreview/PostPreview.tsx
> +      <PostContent>{previewTitle}...</PostContent>
ellipsis 와 컨텐츠 길이를 동시에 설정해놓았습니다!

마지막줄이 꽉 채우게 되면 말 줄임표를 하더라도 컨텐츠가 더 있다는 느낌을 주지 못하게 되더라구요.
그래서 최대 글자를 100글자로 제한해서 잘라놓았습니다!

2023-09-12 04:43 UTC, suyeon1218 commented on src/components/PostPreview/PostPreview.tsx
> +}
아하..! Pick 을 사용해서 받을 수 있군요! 배워갑니다!

2023-09-12 05:21 UTC, suyeon1218 commented on src/components/PostPreview/PostPreview.tsx
> +  const PostHeader = noneProfile === true ? PostHeaderWithUser : PostDetailInfo;
userProfile 에 들어간 경우 프로필을 보여주지 않습니다!

또 `noneProfile` 을 통해 && 연산자를 사용하여 필요한 경우 Profile 을 추가하는 방식으로 변경하였습니다!

2023-09-12 05:22 UTC, suyeon1218 commented on src/components/PostPreview/PostPreview.style.ts
> +  align-items: center;
지금은 에러가 나네요..!! 추후 리팩토링시 반영하겠습니다!!

2023-09-12 05:23 UTC, suyeon1218 commented on src/components/PostPreview/PostPreview.style.ts
> +  color: ${({ theme }) => theme['greyLight']};
다른 컴포넌트들도 수정해야겠군요 ㅠㅠ

2023-09-12 05:27 UTC, merged

2023-09-12 05:28 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.style.ts
> +  align-items: center;
지금 에러 나나요??? 지금은 머지 완료돼서 에러가 안나여 정상인데 뭘까요ㅠㅠ

2023-09-12 05:29 UTC, hyesung99 commented on src/components/PostPreview/PostPreview.style.ts
> +  color: ${({ theme }) => theme['greyLight']};
제가 기존에 사용하던 컴포넌트는 다 수정해놨습니다!