✨Feat : 프로필 변경
prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong pull request #41
Opened 2023-09-14 09:06 UTC by hyesung99

## 🪄 변경사항
1. 프로필 수정 api추가
2. editMode로 프로필 변경, 배경 변경 버튼 보여줄지 판단
3. 프로필 수정 요청 로딩 처리 (spinner 공통 컴포넌트 추가)
4. 프로필 수정 요청 완료시 프로필 데이터 refetch

## ✏️ PR 포인트
refetch 함수를 넘겨주는 depth가 꽤 큰데 어떻게 하면 될까요 ...ㅠ

2023-09-14 15:08 UTC, sscoderati requested changes
혜성님 프로필 변경 기능 구현 고생하셨습니다! p2 이상의 리뷰만 반영해주세요!
refetch는 저도 고민해보았는데 전역 상태로 관리하는게 적절해보이네요..!

2023-09-14 15:08 UTC, sscoderati commented on src/pages/profile/components/ProfileCover/ProfileCover.tsx
> +  const handleFileChange = async (
p3;
이 handleChange가 async 함수인 이유가 있을까요?

2023-09-14 15:08 UTC, sscoderati commented on src/pages/profile/components/ProfileInfo/ProfileAvatarEdit.tsx
> +  });
p3;
ProfileCover에 있는 로직과 동일해보이는데, 재사용 할 수 있을까요?

2023-09-15 05:18 UTC, sscoderati approved these changes

2023-09-15 06:17 UTC, suyeon1218 approved these changes
큰 이슈는 아닌 거 같아서 혜성님이 필요하신 것 고쳐주시면 됩니다!

2023-09-15 06:17 UTC, suyeon1218 commented on src/pages/profile/components/ProfileCover/ProfileCover.tsx
> +  };
### p3

handleSuccess 가 로딩을 끝낸다는 의미라면 handleMutate 도 로딩을 시작한다는 의미를 담을 수 있도록 변수명에 통일성이 있으면 좋겠어요!

2023-09-15 07:13 UTC, merged