✨Feat : header/searchUI & API
prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong pull request #59
Opened 2023-09-20 07:37 UTC by nayeon-hub

## 🪄 변경사항
검색 UI 구현 및 API 연결했습니다.
검색어를 입력하면 해당 내용이 post인지 user인지에 따라 결과값이 다르게 보여집니다.

## 🖥 결과 화면
<img width="194" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/65156388/66a50f05-9e47-45c0-a802-84623d27c519">

## ✏️ PR 포인트
봐야 할 코드가 많습니다ㅠㅠ 다음부터는 PR 코드가 많아지지 않도록 미리 미리 PR을 하도록 하겠습니다...!

+) 스타일 구현 아직입니다 ㅎㅎ input 입력 시 debounce 넣을 예정입니다!

헤더의 컴포넌트 구조입니다. 
컴포넌트들을 좀 쪼개봤어요.. 적당히 쪼갰는지 궁금합니다!
<img width="445" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_NIRVANA_Gidong/assets/65156388/b4dc39de-1322-4d3e-a4ca-7bd472c5def7">

2023-09-20 16:01 UTC, sscoderati requested changes
나연님 검색 기능 구현 쉽지 않으셨을텐데 고생하셨습니다~!
오늘 코어타임 시작하면 승인 눌러놓을게요!

리뷰를 마무리하는 시점에서 고민 포인트 : 전체적으로 활용되는 `search` Prop의 네이밍이 적절한가...?

2023-09-21 05:09 UTC, sscoderati approved these changes

2023-09-21 06:16 UTC, nayeon-hub commented on src/pages/layout/components/SearchMain.tsx
> +  const value = checkHasIncode(inputValue);
checkHasIncode를 util로 뺄 예정인데 함수 내용을 봤을 때는 입력값을 encoding 해주는 역할이라서 incodeValue라는 함수는 어떨까요?

2023-09-21 06:26 UTC, nayeon-hub commented on src/pages/layout/components/Search.tsx
> +      {true && <SearchMain inputValue={inputValue} />}
앗 이게 테스트용으로 넣은 거였어요 허헛,, 빼겠습니다!!

2023-09-21 06:29 UTC, nayeon-hub commented on src/pages/layout/components/EtcNav.tsx
> +  handleShowSearch: () => void;
제가 변수명을 다 대충 지었네요 하핫.. 전체 search 컴포넌트에서 쓰는 props 변수도 수정하겠습니다!!

2023-09-21 07:14 UTC, suyeon1218 approved these changes
나연님 만든다고 수고 많으셨어요!! 리뷰 notice 해주셔서 감사해요~!!

2023-09-21 07:14 UTC, suyeon1218 commented on src/pages/layout/components/SearchMain.tsx
> +  };
### p2

정규표현식의 경우엔 전체 컴포넌트에서 공통되게 사용할 수 있지만 이런 것도 header 폴더 util 폴더에 넣어놓으면 더 코드가 깔끔해질 거 같아요!

2023-09-21 07:14 UTC, suyeon1218 commented on src/pages/layout/components/SearchMain.style.ts
> +  height: 670px;
저희가 모바일 기준으로 해서, height 는 변동될 일이 잘 없다보니 min-height & max-height 과 함께 % 를 사용해야 크기가 너무 작아지거나 커지는 걸 방지할 수 있을 거 같아요~

2023-09-21 07:14 UTC, suyeon1218 commented on src/pages/layout/components/SearchMain.tsx
> +    }
### 궁금증

axios 요청을 할 때 애초에 post 와 user 데이터를 다르게 받아오는데 해당 필터 과정을 한번 더 거치는 이유가 무엇인가요?!

2023-09-21 07:18 UTC, nayeon-hub commented on src/pages/layout/components/SearchMain.tsx
> +    }
post 데이터는 요청 url이 all로 되어있어서 post와 user 데이터 모두 오더라구요ㅠㅠ

2023-09-21 07:40 UTC, merged